# Site settings
title: "我不是熊猫人"
header-img: "img/green.jpg"
tagline: "cn"  
description: "Pandaman's Blog"  
baseurl: ""
url: "http://blog.zhaohengbo.com"  

# About/contact
owner: 
  name: "Pandaman"
  email: mail@zhaohengbo.com
  bio: "简约而不简单"

# Data
gavatar: "img/pandaman.jpg"
favicon: "img/favicon.ico"

douban_username:  
twitter_username: 
github_username: "ceares"
facebook_username: 
weibo_username: 
zhihu_username: 

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  


markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

kramdown:
  input: GFM
  auto_ids:         true
  footnote_nr:      [1]
  entity_output:    as_char
  toc_levels:       1..3
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: true

coderay:
  coderay_line_numbers: inline
  coderay_line_numbers_start: 1
  coderay_tab_width: 4

  
mathjax:            true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Beijing

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Pandaman"
      header-img: "img/blue.jpg" # We don't want posts without a header image, that whould mean white on white
      categories: "blog"
      description: "http://blog.zhaohengbo.com" 
      permalink: "/:title"

# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : "pandaman"
  disqus :
      short_name : 

# Analytics and webmaster tools stuff goes here
google_analytics: 
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
