# Site settings
title: "我不是熊猫人"
header-img: "rgba(57,86,149,1)"
tagline: "cn"  
description: "Pandaman's Blog"  
baseurl: ""
url: "http://blog.zhaohengbo.com"  

# About/contact
owner: 
  name: "Pandaman"
  email: mail@zhaohengbo.com
  bio: "简约而不简单"

# Data
gavatar: "img/res/pandaman.jpg"
favicon: "img/res/favicon.ico"

douban_username:  
twitter_username: 
github_username: "ceares"
facebook_username: 
weibo_username: 
zhihu_username: 

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  


markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 8
exclude: ["README.md","update.bat"]

kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..2
  enable_coderay:   false
mathjax:            true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Beijing

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Pandaman"
      header-img: "rgba(20,84,109,1)" 
      categories: "blog"
      description: "http://blog.zhaohengbo.com" 
      permalink: "/:title"

# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : "pandaman"
  disqus :
      short_name : 

# Analytics and webmaster tools stuff goes here
google_analytics: 
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
